### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by emskigdot** [santhalakshminarayana/AutoML#1]
Dear @santhalakshminarayana,

I just found your GUI for Machine Learning tasks. It looks very nice and extremely user friendly. As I didn't find any license text, I wonder, under which license your work is published. Would you be so kind to add this information to you repository?
Would be very appreciated.

**Comment by santhalakshminarayana** [comment]
Hi @emskigdot, I didn't find any need to include license as it is open source work that any one can use. Anyway thank you for suggestion of adding license. I have added license and hope you use my work to make better projects than me.

**Comment by emskigdot** [comment]
Thanks a lot, @santhalakshminarayana.
If you wonder, why I asked you for a license, find the information [here](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository).
As long you publish your code without a license, it is not really open source, since

> you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.
